config/routes.rb
Rails.application.routes.draw do
  resources :shop_schedules

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
	    registrations: 'admins/registrations'
  }
  root "shops#index"

  resources :shops

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_schedules, dependent: :destroy
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[update destroy create new]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
    @today_schedule = @shop.shop_schedules.find_by(day: Date.today.strftime("%A"))
    @upcomming_schedules = @shop.shop_schedules.where.not(day: Date.today.strftime("%A"))
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to root_path, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div class="w-50">
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>
      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex text-center justify-content-center">
    <%= form.text_field :name, placeholder:"Enter Name", class:"form-control w-50" %>
  </div>
  <div class="text-center">
    <%= form.submit t(:update), class:"mt-3 btn btn-success" %>
    <br/>
    <%= link_to t(:back_to_shops), shops_path, class:"btn btn-sm" %>
  </div>
<% end %>
</div>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>

</div>

app/views/shops/edit.html.erb
<div class="container">
  <h1 class="text-center mt-5"><%= t(:editing_shop) %></h1>
  <div class="d-flex justify-content-center">
    <%= render "form", shop: @shop %>
  </div>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center"><%= t(:shops) %></h1>
<div id="shops" class="container">
  <table class="table table-bordered text-center table-striped">
    <thead class="table-dark">
      <tr>
        <th><%= t(:shop_list)%></th>
        <th><%= t(:status) %></th>
      </tr>
    </thead>
    <tbody>
      <% @shops.each do |shop| %>
        <tr style="text-align: center;">
          <td>
          <%= link_to shop, style:"text-decoration: none" do %>
            <%= shop.name  %>
          <% end %>
          </td>
          <td>
            <%
            status = shop.shop_schedules.find_by(day: Date.today.strftime("%A") )
            %>
            <%= status && status.day_status %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <table>
</div>

app/views/shops/new.html.erb
<div class="container">
  <h3 class="text-center mt-5">New shop</h3>
  <div class="d-flex justify-content-center">
    <%= render "form", shop: @shop %>
  </div>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container-fluid">
<div class="container d-flex justify-content-between">
  <div class="text-center" style="width: 45%; ">
    <h2 style=""><%= @shop.name %></h2>
  </div>
  <div class="p-5" style="box-shadow: 2px 2px 7px black; width: 45%; border-radius: 15px;">
    <% unless (@shop.shop_schedules.present?)%>
      <p class="text-center">No Schedules Right Now!</p>
    <% end %>
    <% if @today_schedule.present? && @today_schedule.day_status != "Closed" %>
      <p style="line-height: 5px;" class="mt-3 fw-bold"><%= t(:hours)%> &nbsp; <%= @today_schedule.day %> <%= @today_schedule.opening_time && @today_schedule.opening_time.strftime("%H:%M")%> - <%= @today_schedule.half_time && @today_schedule.half_time.strftime("%H:%M") %>, <%= @today_schedule.open_after_half_time && @today_schedule.open_after_half_time.strftime("%H:%M")%> - <%= @today_schedule.closing_time && @today_schedule.closing_time.strftime("%H:%M") %> </p>
    <% elsif @today_schedule.present? && @today_schedule.day_status == "Closed" %>
      <p style="line-height: 5px;" class="mt-3 fw-bold"><%= t(:hours)%> &nbsp; <%= t"#{@today_schedule.day}" %> <%= @today_schedule.day_status %></p>
    <% end %>

    <% if @upcomming_schedules.present? %>
      <% @upcomming_schedules.each do |schedule| %>
          <% if schedule.day_status != "Closed"  %>
            <p style="line-height: 7px; padding-left: 70px;"><%= schedule.day %> <%= schedule.opening_time && schedule.opening_time.strftime("%H:%M")%> - <%= schedule.half_time && schedule.half_time.strftime("%H:%M") %>, <%= schedule.open_after_half_time && schedule.open_after_half_time.strftime("%H:%M")%> - <%= schedule.closing_time && schedule.closing_time.strftime("%H:%M") %> </p>
          <% elsif schedule.day_status == "Closed"  %>
            <p style="line-height: 7px; padding-left: 70px;"><%= schedule.day %> <%= schedule.day_status %></p>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>
  <div class="mt-5 d-flex flex-column align-items-center">
    <div  class="w-50 text-center">
      <%= link_to t(:back_to_shops), root_path, class:"btn btn-dark", style:"min-width: 20%; width: auto;" %>
    </div>
    <div class="d-flex text-center justify-content-center w-50 mt-2">
      <% if admin_signed_in? %>
        <%= link_to t(:edit), edit_shop_path(@shop), class:"text-light btn btn-info", style:"margin-right: 5px; width: auto" %>
        <%= button_to t(:destroy), @shop, method: :delete, class:"btn btn-danger" %>
        <% end %>
      </div>
  </div>
</div>