config/routes.rb
Rails.application.routes.draw do
  resources :shop_schedules

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
	    registrations: 'admins/registrations'
  }
  root "shops#index"

  resources :shops

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/shop_schedule.rb
class ShopSchedule < ApplicationRecord
  belongs_to :shop, optional: true

  DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday' ]
  DAY_STATUS = ['Working Day', 'Closed']

  enum day: {
  "Monday" => "monday",
  "Tuesday" => "tuesday",
  "Wednesday" => "wednesday",
  "Thursday" => "thursday",
  "Friday" => "friday",
  "Saturday" => "saturday",
  "Sunday" => "sunday"
  }
  enum day_status: {
      "Working Day" => "Working Day",
      "Closed" => "closed"
  }
end

app/controllers/shop_schedules_controller.rb
class ShopSchedulesController < ApplicationController
  before_action :set_shop_schedule, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[update destroy create new]

  def index
    @shop_schedules = ShopSchedule.all
  end


  def show
  end

  def new
    @shops = Shop.all
    @shop_schedule = ShopSchedule.new
  end

  def edit
    @shops = Shop.all
  end

  def create
    @shop_schedule = ShopSchedule.new(shop_schedule_params)
    shop_id = shop_schedule_params[:shop_id]
    respond_to do |format|
      if @shop_schedule.save
        format.html { redirect_to shop_path(shop_id), notice: "Shop schedule was successfully created." }
        format.json { render :show, status: :created, location: @shop_schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop_schedule.update(shop_schedule_params)
        format.html { redirect_to shop_schedule_url(@shop_schedule), notice: "Shop schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @shop_schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop_schedule.destroy

    respond_to do |format|
      format.html { redirect_to shop_schedules_url, notice: "Shop schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_shop_schedule
      @shop_schedule = ShopSchedule.find(params[:id])
    end

    def shop_schedule_params
      params.require(:shop_schedule).permit(:day, :opening_time, :half_time, :open_after_half_time, :closing_time, :day_status, :shop_id)
    end
end

app/helpers/shop_schedules_helper.rb
module ShopSchedulesHelper
end

app/views/shop_schedules/_form.html.erb
 <%= form_with(model: shop_schedule) do |form| %>
    <% if shop_schedule.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(shop_schedule.errors.count, "error") %> prohibited this shop_schedule from being saved:</h2>

        <ul>
          <% shop_schedule.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex flex-column justify-content-center align-items-center text-center">
      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:day), style: "display: block; margin-right: 10px;" %>
        <%= form.select :day, ShopSchedule::DAYS, :selected => shop_schedule.day %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:opening_time), style: "display: block" %>
        <%= form.time_field :opening_time %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:half_time), style: "display: block" %>
        <%= form.time_field :half_time %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:after_half_time), style: "display: block" %>
        <%= form.time_field :open_after_half_time %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:closing_time), style: "display: block" %>
        <%= form.time_field :closing_time %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:day_status), style: "display: block" %>
        <%= form.select :day_status, ShopSchedule::DAY_STATUS, :selected => shop_schedule.day_status %>
      </div>

      <div class="d-flex justify-content-between mt-3" style="width: 25%">
        <%= form.label t(:shop), style: "display: block" %>
        <%= form.collection_select :shop_id, @shops.order(:id),:id,:name %>
      </div>

      <div class="mt-4">
        <%= form.submit t(:update),class:"btn btn-success" %>
      </div>
      <div>
        <%= link_to t(:back_to_schedules), shop_schedules_path, class:"btn btn-sm" %>
      </div>
    </div>

  <% end %>

app/views/shop_schedules/_shop_schedule.html.erb
<div id="<%= dom_id shop_schedule %>">
  <p>
    <strong>Day:</strong>
    <%= shop_schedule.day %>
  </p>

  <p>
    <strong>Opening time:</strong>
    <%= shop_schedule.opening_time %>
  </p>

  <p>
    <strong>Half time:</strong>
    <%= shop_schedule.half_time %>
  </p>

  <p>
    <strong>Open after half time:</strong>
    <%= shop_schedule.open_after_half_time %>
  </p>

  <p>
    <strong>Closing time:</strong>
    <%= shop_schedule.closing_time %>
  </p>

  <p>
    <strong>Day status:</strong>
    <%= shop_schedule.day_status %>
  </p>

</div>

app/views/shop_schedules/edit.html.erb
<div class="container">
  <h2 class="text-center mt-3"><%= t(:editing_schedule) %></h2>
  <div>
    <%= render "form", shop_schedule: @shop_schedule %>
  </div>
</div>

app/views/shop_schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h3 class="text-center">Shop schedules</h3>
  <div id="shop_schedules">
    <table class="table table-bordered table-striped shadow ">
      <thead class="table-dark">
        <tr>
          <th><%= t(:day) %></th>
          <th><%= t(:opening_time) %></th>
          <th><%= t(:half_time) %></th>
          <th><%= t(:after_half_time) %></th>
          <th><%= t(:closing_time) %></th>
          <th><%= t(:day_status) %></th>
          <th><%= t(:shop) %></th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @shop_schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.day %></td>
            <td><%= schedule.opening_time && schedule.opening_time.strftime("%H:%m:%S")  %></td>
            <td><%= schedule.half_time && schedule.half_time.strftime("%H:%m:%S") %></td>
            <td><%= schedule.open_after_half_time && schedule.open_after_half_time.strftime("%H:%m:%S") %></td>
            <td><%= schedule.closing_time && schedule.closing_time.strftime("%H:%m:%S") %></td>
            <td><%= schedule.day_status %></td>
            <td><%= schedule.shop && schedule.shop.name %></td>
            <td><%= link_to "Show", schedule, class:"btn btn-dark btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shop_schedules/new.html.erb
<div class="d-flex container flex-column">
  <h3 class="text-center mt-4"><%= t(:new_schedule) %></h3>
  <div>
    <%= render "form", shop_schedule: @shop_schedule %>
  </div>
</div>

app/views/shop_schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container d-flex align-items-center flex-column">
  <div class="card p-1 shadow w-100">
  <table class="table table-striped m-0">
    <thead class="table-dark text-center">
      <tr>
        <th colspan="2"><h2><%= t(:schedule) %></h2></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= t(:day) %></td>
        <td><%= @shop_schedule.day %></td>
      </tr>
      <tr>
        <td><%= t(:opening_time) %></td>
        <td><%= @shop_schedule.opening_time && @shop_schedule.opening_time.strftime('%H:%M:%S') %></td>
      </tr>
      <tr>
        <td><%= t(:half_time) %></td>
        <td><%= @shop_schedule.half_time && @shop_schedule.half_time.strftime('%H:%M:%S') %></td>
      </tr>
      <tr>
        <td><%= t(:after_half_time) %></td>
        <td><%= @shop_schedule.open_after_half_time && @shop_schedule.open_after_half_time.strftime('%H:%M:%S') %></td>
      </tr>
      <tr>
        <td><%= t(:closing_time) %></td>
        <td><%= @shop_schedule.closing_time && @shop_schedule.closing_time.strftime('%H:%M:%S') %></td>
      </tr>
      <tr>
        <td><%= t(:day_status) %></td>
        <td><%= @shop_schedule.day_status %></td>
      </tr>
      <tr>
        <td><%= t(:shop) %></td>
        <td><%= @shop_schedule.shop && @shop_schedule.shop.name %></td>
      </tr>

    </tbody>
  </table>
  </div>


  <% if admin_signed_in? %>
    <div class="d-flex mt-3">
      <%= link_to t(:edit), edit_shop_schedule_path(@shop_schedule), class:"btn btn-warning btn-sm me-2" %>
      <%= link_to t(:shops), root_path, class:"btn btn-dark btn-sm me-2" %>

      <%= button_to t(:destroy), @shop_schedule, method: :delete, class:"btn btn-danger btn-sm" %>
    </div>
  <% end %>
</div>