config/routes.rb
Rails.application.routes.draw do
  resources :shop_schedules

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
	    registrations: 'admins/registrations'
  }
  root "shops#index"

  resources :shops

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= t(:shop_schedules) %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><%= t(:home) %></a>
        </li>
        <% if admin_signed_in? %>
            <li class="nav-item">
                <%= link_to t(:new_shop) , new_shop_path, class:"btn " %>
            </li>
            <li class="nav-item">
                <%= link_to t(:schedule_list), shop_schedules_path, class:"btn" %>
            </li>
            <li class="nav-item">
              <%= link_to t(:new_schedule), new_shop_schedule_path, class:"btn" %>
            </li>
        <% end %>
      </ul>
      <% if admin_signed_in? %>
        <span class="navbar-text">
            <%= button_to "Sign Out", destroy_admin_session_path, method: :delete, class:"btn" %>
        </span>
        <span>
          <%= link_to t(:profile), edit_admin_registration_path(current_admin), class:"btn" %>
        </span>
      <% end %>
      <li class="dropdown nav-item" style="list-style-type: none;">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Lang
          </a>
          <ul class="dropdown-menu" style="right: 0px;" aria-labelledby="navbarScrollingDropdown">
            <li><%= link_to "Fr", controller: controller_name, action: action_name, locale: "fr"  %></li>
            <li><%= link_to "Eng", controller: controller_name, action: action_name, locale: "en"  %></li>
          </ul>
          </li>
    </div>
  </div>
</nav>


<style>
.dropdown-menu[data-bs-popper] {
  min-width: 30%;
  width: 118%;
  padding-left: 10px;
  right: 0px !important;
  left: auto
}

.dropdown-menu a{
  text-decoration: none;
  color: black;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopScheduleManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>